/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FILES           2
#define MMAP_ASSETS_CHECKSUM        0xCFF6

enum MMAP_ASSETS_LISTS {
    MMAP_ASSETS_FONT_PUHUI_COMMON_14_1_BIN = 0,        /*!< font_puhui_common_14_1.bin */
    MMAP_ASSETS_FONT_PUHUI_COMMON_20_4_BIN = 1,        /*!< font_puhui_common_20_4.bin */
};
